apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "safe-config.fullname" . }}-media
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-config.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  accessModes: {{ .Values.persistence.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeMode: Filesystem