## @section Common parameters
##

## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""

## @section Installation Parameters
##

## @param replicas Replicas for deployment
##
replicas: 1

## @param strategy Strategy for deployment
##
strategy: "Recreate"

## @param commonLabels [object] Labels to add to all related objects
##
commonLabels: {}

## @param commonAnnotations [object] Annotations to to all related objects
##
commonAnnotations: {}

ingress:
  ## @param ingress.ingressClassName Name of the ingress class name to be used
  ##
  ingressClassName: ""

  ## @param ingress.hostname Default host for the ingress record
  ##
  hostname: safe-client-gateway.cluster.local

  ## @param ingress.annotations Annotations to be added to ingress resources
  ## @skipingress.annotations
  ##
  annotations: {}

## @param nodeSelector Object containing node selection constraint to deployment
## https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
##
nodeSelector: {}

## @param resources Resource specification to deployment
##
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## @param tolerations Tolerations specifications to deployment
##
tolerations: []

## @param affinity Affinity specifications to deployment
##
affinity: {}

image:
  ## @param image.registry Docker registry to deployment
  ##
  registry: registry.hub.docker.com

  ## @param image.repository Docker image repository to deployment
  ##
  repository: safeglobal/safe-client-gateway-nest

  ## @param image.tag Docker image tag to deployment
  ##
  tag: ""

  ## @param image.pullPolicy Pull policy to deployment as deinfed in
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

service:
  ## @param service.type service type
  ##
  type: ClusterIP
  ports:
    ## @param service.ports.number service port number
    ##
    number: 3000
    ## @param service.ports.name service port name
    ##
    name: api
  ## @param service.sessionAffinity Control where client requests go, to the same pod or round-robin
  ## Values: ClientIP or None
  ## ref: https://kubernetes.io/docs/user-guide/services/
  ##
  sessionAffinity: None

## @section Config Service Parameters

config:
  httpClient:
    ## @param config.httpClient.requestTimeout Timeout in milliseconds
    ##
    requestTimeout: "60000"
  ## @param config.safeConfig.url Url of the safe Config service
  ##
  safeConfig:
    url: ""
  ## @param config.exchange_api.url The base Exchange Rate API to be used.
  ##
  exchange_api:
    url: http://api.exchangeratesapi.io/v1

  redis:
    ## @param config.redis.host Redis server host
    host: ""
    ## @param config.redis.port Redis server port
    port: "6379"

  ## @param config.authToken Authentication token to access safe-client-gateway API requests
  authToken: ""
  ## @param config.infuraApiKey Infura API key
  infuraApiKey: ""
  ## @param config.relaysProviderApiKeyArbitrumOne Relay provider API key for Arbitrum One
  relaysProviderApiKeyArbitrumOne: ""

  log:
    ## @param config.log.level Log level
    level: info
    ## @param config.log.silent Silent mode
    silent: "false"

  alertsProvider:
    ## @param config.alertsProvider Alerts provider signing key
    signingKey: ""
    ## @param config.alertsProvider Alerts provider apiKey
    apiKey: ""
    ## @param config.alertsProvider Alerts provider account
    account: ""
    ## @param config.alertsProvider Alerts provider project
    project: ""

  emailApi:
    applicationCode: ""
    fromEmail: "changeme@example.com"
    apiKey: ""
  emailTemplate:
    recoveryTx: ""
    unknownRecoveryTx: ""
    verificationCode: ""
  relayProvider:
    apiKeyGnosisChain: ""
    apiKeySepolia: ""

  ## @param config.secretReferenceKey Reference to an existing secret containing the following entries: AUTH_TOKEN
  ##
  secretReferenceKey: ""

  ## @param config.extraEnvVars [object] Add additional extra environment vairables to the configMap
  ##
  extraEnvVars: {}
