---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safe-client-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-client-gateway.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
data:
  HTTP_CLIENT_REQUEST_TIMEOUT_MILLISECONDS: {{ .Values.config.httpClient.requestTimeout | quote }}
  SAFE_CONFIG_BASE_URI: {{ .Values.config.safeConfig.url | quote }}
  EXCHANGE_API_BASE_URI: {{ .Values.config.exchange_api.url | quote }}
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
  LOG_LEVEL: {{ .Values.config.log.level | quote }}
  LOG_SILENT: {{ .Values.config.log.silent | quote }}
  ALERTS_PROVIDER_SIGNING_KEY: {{ .Values.config.alertsProvider.signingKey | quote }}
  ALERTS_PROVIDER_API_KEY: {{ .Values.config.alertsProvider.apiKey | quote }}
  ALERTS_PROVIDER_ACCOUNT: {{ .Values.config.alertsProvider.account | quote }}
  ALERTS_PROVIDER_PROJECT: {{ .Values.config.alertsProvider.project | quote }}
  EMAIL_API_APPLICATION_CODE: {{ .Values.config.emailApi.applicationCode | quote }}
  EMAIL_API_FROM_EMAIL: {{ .Values.config.emailApi.fromEmail | quote }}
  EMAIL_API_KEY: {{ .Values.config.emailApi.apiKey | quote }}
  EMAIL_TEMPLATE_RECOVERY_TX: {{ .Values.config.emailTemplate.recoveryTx | quote }}
  EMAIL_TEMPLATE_UNKNOWN_RECOVERY_TX: {{ .Values.config.emailTemplate.unknownRecoveryTx | quote }}
  EMAIL_TEMPLATE_VERIFICATION_CODE: {{ .Values.config.emailTemplate.verificationCode | quote }}
  {{- if .Values.config.extraEnvVars }}
  {{ .Values.config.extraEnvVars | toYaml | nindent 2 }}
  {{- end }}
