{{- if not .Values.config.secretReferenceKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-client-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-client-gateway.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  AUTH_TOKEN: {{ .Values.config.authToken | b64enc }}
  INFURA_API_KEY: {{ .Values.config.infuraApiKey | b64enc }}
  RELAY_PROVIDER_API_KEY_ARBITRUM_ONE: {{ .Values.config.relaysProviderApiKeyArbitrumOne | b64enc }}
{{- end }}
