{{- if not .Values.config.secretReferenceKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-client-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-client-gateway.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  AUTH_TOKEN: {{ .Values.config.authToken | b64enc }}
  INFURA_API_KEY: {{ .Values.config.infuraApiKey | b64enc }}
  RELAY_PROVIDER_API_KEY_ARBITRUM_ONE: {{ .Values.config.relaysProviderApiKeyArbitrumOne | b64enc }}
  RELAY_PROVIDER_API_KEY_OPTIMISM: {{ .Values.config.relaysProviderApiKeyOptimism | b64enc }}
  RELAY_PROVIDER_API_KEY_BSC: {{ .Values.config.relaysProviderApiKeyBsc | b64enc }}
  RELAY_PROVIDER_API_KEY_POLYGON: {{ .Values.config.relaysProviderApiKeyPolygon | b64enc }}
  RELAY_PROVIDER_API_KEY_POLYGON_ZKEVM: {{ .Values.config.relaysProviderApiKeyPolygonZkEvm | b64enc }}
  RELAY_PROVIDER_API_KEY_BASE: {{ .Values.config.relaysProviderApiKeyBase | b64enc }}
  RELAY_PROVIDER_API_KEY_AVALANCHE: {{ .Values.config.relaysProviderApiKeyAvalanche | b64enc }}
  RELAY_PROVIDER_API_KEY_LINEA: {{ .Values.config.relaysProviderApiKeyLinea | b64enc }}
  RELAY_PROVIDER_API_KEY_BLAST: {{ .Values.config.relaysProviderApiKeyBlast | b64enc }}
  FINGERPRINT_ENCRYPTION_KEY: {{ .Values.config.fingerprintEncryptionKey | b64enc }}
  JWT_ISSUER: {{ .Values.config.jwtIssuer | b64enc }}
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc }}
  PUSH_NOTIFICATIONS_API_PROJECT: {{ .Values.config.pushNotificationsApiProject | b64enc }}
  PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_CLIENT_EMAIL: {{ .Values.config.pushNotificationsApiServiceAccountClientEmail | b64enc }}
  PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_PRIVATE_KEY: {{ .Values.config.pushNotificationsApiServiceAccountPrivateKey | b64enc }}
  STAKING_API_KEY: {{ .Values.config.stakingApiKey | b64enc }}
  STAKING_TESTNET_API_KEY: {{ .Values.config.stakingTestnetApiKey | b64enc }}
{{- end }}
