---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe-transaction.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas.scheduler }}
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
      app.kubernetes.io/instance: {{ include "safe-transaction.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/instance: {{ include "safe-transaction.name" . }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: scheduler
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ docker/web/celery/scheduler/run.sh ]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        resources: {{- toYaml .Values.resources.scheduler | nindent 12 }}
        envFrom:
          - configMapRef:
              name: {{ include "safe-transaction.fullname" . }}
          - secretRef:
              {{- if .Values.config.secretReferenceKey }}
              name: {{ .Values.config.secretReferenceKey }}
              {{- else }}
              name: {{ include "safe-transaction.fullname" . }}
              {{- end }}
          - secretRef:
              name: {{ include "safe-transaction.postgres-secret" . }}
          - secretRef:
              name: {{ include "safe-transaction.redis-secret" . }}
          - secretRef:
              name: {{ include "safe-transaction.rabbitmq-secret" . }}
        volumeMounts:
          - name: tmp-volume
            mountPath: /tmp
      serviceAccountName: {{ include "safe-transaction.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}

