---
{{- if not .Values.config.redisTransaction.secretReferenceKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-transaction.fullname" . }}-redis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  password:  {{ .Values.config.redisTransaction.password | b64enc }}
  REDIS_URL: "{{- printf "redis://%s:%s@%s:%s/%s" .Values.config.redisTransaction.username .Values.config.redisTransaction.password .Values.config.redisTransaction.host .Values.config.redisTransaction.port .Values.config.redisTransaction.database | b64enc -}}"
{{- end }}
